CREATE TABLE `merchant_certification` (
  `certification_id` varchar(32) NOT NULL COMMENT '申请认证编号',
  `member_id` varchar(32) NOT NULL COMMENT '商户id',
  `member_name` varchar(20) DEFAULT NULL COMMENT '商户名称',
  `fbuslicence` varchar(300) DEFAULT NULL COMMENT '营业执照图片',
  `unified_number` varchar(32) DEFAULT NULL COMMENT '统一编号',
  `certification_name` varchar(20) DEFAULT NULL COMMENT '商户法人名字',
  `certification_card` varchar(20) DEFAULT NULL COMMENT '商户法人身份证号',
  `mobile` varchar(11) DEFAULT NULL COMMENT '商户手机号',
  `certification_state` int(1) NOT NULL DEFAULT '0' COMMENT '状态:0待审核,1审核通过,2审核拒绝',
  `certification_time` datetime NOT NULL COMMENT '申请认证时间',
  `certification_refuse_caused` varchar(100) DEFAULT NULL COMMENT '认证失败原因',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `auditor_id` varchar(20) NOT NULL COMMENT '审核人id',
  --`forgcode` varchar(300) DEFAULT NULL COMMENT '组织代码图片',
  --`flawholder` varchar(300) DEFAULT NULL COMMENT '法人持证件照图片',
  --`ffrontid` varchar(300) DEFAULT NULL COMMENT '身份证正面图片',
  --`fbackid` varchar(300) DEFAULT NULL COMMENT '身份证反面图片',
  --`fspequalifione` varchar(300) DEFAULT NULL COMMENT '特殊资质一图片',
  --`fspequalifitwo` varchar(300) DEFAULT NULL COMMENT '特殊资质二图片',
  --`fspequalifithree` varchar(300) DEFAULT NULL COMMENT '特殊资质三图片',
  --`fspequalififour` varchar(300) DEFAULT NULL COMMENT '特殊资质四图片',
  --`fspequalififive` varchar(300) DEFAULT NULL COMMENT '特殊资质五图片',
  --`ffront` varchar(300) DEFAULT NULL COMMENT '身份证正面照片',
  --`fback` varchar(300) DEFAULT NULL COMMENT '身份证反面照片',
  --`fbuslicence_name` varchar(400) DEFAULT NULL COMMENT '营业执照图片名称',
  --`forgcode_name` varchar(400) DEFAULT NULL COMMENT '组织代码图片名称',
  --`flawholder_name` varchar(400) DEFAULT NULL COMMENT '法人持证件照名称',
  --`ffrontid_name` varchar(400) DEFAULT NULL COMMENT '身份证正面图片名称',
  --`fbackid_name` varchar(400) DEFAULT NULL COMMENT '身份证反面图片名称',
  --`fspequalifione_name` varchar(400) DEFAULT NULL COMMENT '特殊资质一图片名称',
  --`fspequalifitwo_name` varchar(400) DEFAULT NULL COMMENT '特殊资质二图片名称',
  --`fspequalifithree_name` varchar(400) DEFAULT NULL COMMENT '特殊资质三图片名称',
  --`fspequalififour_name` varchar(400) DEFAULT NULL COMMENT '特殊资质四图片名称',
  --`fspequalififive_name` varchar(400) DEFAULT NULL COMMENT '特殊资质五图片名称',
  --`ffront_name` varchar(400) DEFAULT NULL COMMENT '身份证正面照片名称',
  --`fback_name` varchar(400) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '身份证反面照片名称',
  PRIMARY KEY (`certification_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户认证表';
