CREATE TABLE `merchant` (
  `fid` varchar(32) NOT NULL  COMMENT '商户ID',
  --`fmer_code` varchar(16) DEFAULT NULL COMMENT '商户编码',
  --`fmer_pcode` varchar(16) DEFAULT NULL COMMENT '上级商户编码',
  `fmer_name` varchar(18) NOT NULL COMMENT '商户名称',
  `fmobile` varchar(11) NOT NULL COMMENT '电话',
  `flogin_id` varchar(8) default NULL COMMENT '登录id',
  `password` varchar(60) default NULL COMMENT '登录密码',
  -- `fmember_imei` varchar(50) DEFAULT NULL COMMENT 'app登录手机唯一识别码',
  --`fmember_qq_id` varchar(50) DEFAULT NULL COMMENT 'qq三方登录的唯一标示',
  `fmember_openid` varchar(50) DEFAULT NULL COMMENT '微信三方登录唯一标识',
  --`fsys_id` varchar(4) not  NULL COMMENT '系统标识',
  --`fmember_certstate`  int(4) DEFAULT '0' COMMENT '商户审核状态 0待审核,1审核通过,2审核拒绝',
  `fmember_state` TINYINT(1) DEFAULT '1' COMMENT '商户状态 1为开启 0为关闭',
  `expiration_date` datetime NOT NULL COMMENT '有效截止日期',
  
  --`fcreator_id` varchar(16) DEFAULT NULL COMMENT '创建人',
  --`fcreate_time` datetime DEFAULT NULL COMMENT '创建时间',
  --`flast_edit_time` datetime DEFAULT NULL COMMENT '修改时间',
  --`flast_editor_id` varchar(16) DEFAULT NULL COMMENT '修改人',
  --`fdeleted` int(1) DEFAULT '0' COMMENT '删除标识：0-未删除，1-已删除',
  --`fdelete_user_id` varchar(32) DEFAULT NULL COMMENT '删除人',
  --`fmark_deleted_time` datetime(6) DEFAULT NULL COMMENT '删除时间',
  --`fchecker_id` varchar(16) DEFAULT NULL COMMENT '审核人',
  --`fcheck_time` datetime DEFAULT NULL COMMENT '审核时间',
   UNIQUE KEY `UK_merchant_mobile` (`fmobile`),
   UNIQUE KEY `UK_merchant_loginid` (`flogin_id`),
   PRIMARY KEY (`fid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户基本信息（登录用）';